//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace de1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINH_TP
    {
        public TINH_TP()
        {
            this.BIENGIOIs = new HashSet<BIENGIOI>();
            this.TINH_TP1 = new HashSet<TINH_TP>();
            this.TINH_TP2 = new HashSet<TINH_TP>();
        }
    
        public string MA_T_TP { get; set; }
        public string TEN_T_TP { get; set; }
        public Nullable<double> DT { get; set; }
        public Nullable<long> DS { get; set; }
        public string MIEN { get; set; }
    
        public virtual ICollection<BIENGIOI> BIENGIOIs { get; set; }
        public virtual ICollection<TINH_TP> TINH_TP1 { get; set; }
        public virtual ICollection<TINH_TP> TINH_TP2 { get; set; }
    }
}
